/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module checker_1 (
    input sum,
    input carry,
    output reg [1:0] value
  );
  
  
  
  integer z;
  
  always @* begin
    z = 2'h0;
    z = {carry, sum};
    value = z;
  end
endmodule
